### ISSUE TITLE
AMP-Story: data-vars and selector's are not working in Story-Trigger.

### ISSUE THREAD

**Issue by martinfischerextern** [ampproject/wg-analytics#14]
Hello,
We using amp-story for our daily video-news. This Story are separated in 6-9 short videos and we want to track how good every video perform. Every amp-story-page includes one amp-story-grid-layer template="fill" with one amp-video, and maybe an amp-story-page-attachment.

We need to enrich the Story-Trigger (e.g. "on": "story-page-visible") with data of the triggered page/video (e.g. the Content ID, a Name, the length of the included video…).
For this, the data-vars seems to be a good solution. However, it do not work in the Story-Triggers.
Another idea was to generate a special trigger config for every page and use the selector-property to bind the information to the concrete page. However, selector are also not working in story trigger, so it will use only the last config for every event.

I think this features are basic and have to work in every trigger.

An example you will find here:
https://m.bild.de/amp-story/bild-daily/news/ausgabe-64382772,dede,view=amp.bildMobile.html

Thanks,
Martin

**Comment by micajuine-ho** [comment]
Hi Martin,

Thank you for this issue. 

This repo is for the analytics working group updates. Can you instead file this issue in the amphtml repo so it can get fixed? 
https://github.com/ampproject/amphtml/issues/new?assignees=&labels=Type%3A+Bug&template=bug-report.md&title=

Thanks.
